= Webhook Signature Generator Policy

ifdef::env-github[]
image:https://img.shields.io/static/v1?label=Available%20at&message=Gravitee.io&color=1EC9D2["Gravitee.io", link="https://download.gravitee.io/#graviteeio-apim/plugins/policies/gravitee-policy-webook-signature-generator/"]
image:https://img.shields.io/badge/License-Apache%202.0-blue.svg["License", link="https://github.com/gravitee-io/gravitee-policy-webook-signature-generator/blob/master/LICENSE.txt"]
image:https://img.shields.io/badge/semantic--release-conventional%20commits-e10079?logo=semantic-release["Releases", link="https://github.com/gravitee-io/gravitee-policy-webook-signature-generator/releases"]
image:https://circleci.com/gh/gravitee-io/webhook-logo.svg?style=svg["CircleCI", link="https://circleci.com/gh/gravitee-io/gravitee-policy-webook-signature-generator"]
endif::[]

== Phase

[cols="4*", options="header"]
|===
^|onRequest
^|onResponse
^|onMessageRequest
^|onMessageResponse

^.^| -
^.^| X
^.^| -
^.^| X

|===

== Description

Generates a Webhook (HMAC) signature against the outbound HTTP body or Message, and optionally additional custom header(s), to ensure its identity.  Typically used (in a Gravitee V4-Message API) to generate & attach a HMAC signature of an outbound message to a remote Webhook.

HMAC Signatures are a kind of authentication method which is adding a level of security.  It ensures the request has originated from the known source and has not been tampered with.

The sender of the message generates a HMAC signature (typically stored in a header of the request) and is then validated by the receiver using a pre-shared secret.  This policy will generate that signature, and add it into a HTTP header in the outbound message.

The "Signature" is based on the model that the receiver must authenticate itself with a digital signature produced by a shared symmetric key (e.g.: HMAC).  Also known as the shared "secret".

> When combining this policy with the AVRO or Protobuf (binary to text) transformation policies, remember to order that policy beforehand (so this policy receives the message as plain text in order to generate the HMAC signature).

== Configuration

|===
|Property |Required |Description |Default

.^|targetSignatureHeader
^.^|X
|Specify the HTTP header that will contain the generated HMAC signature
^.^| X-HMAC-Signature

.^|schemeType
^.^|X
|By default, this policy will generate the HMAC signature only against the HTTP body.  Set this boolean to 'true' if you need to include additional headers (as well as the HTTP body/message) in the signature generation.
^.^| false

.^|headersDelimiter
^.^|-
|Specify a delimiter to separate each header and the body/message
^.^| .

.^|headers [List]
^.^|-
|List of existing HTTP or Message headers to prepend their values to the body/message for generating the HMAC signature
^.^| 

.^|secret
^.^|X
|The secret key used to generate the HMAC signature
^.^| 

.^|algorithms
^.^|X
|Specify the HMAC algorithm (e.g.: HmacSHA1, HmacSHA256, HmacSHA384, or HmacSHA512)
^.^| HmacSHA256

|===


[source, json]
.Webook Signature Generator Policy example:
----
{
  "policy": "webook-signature-generator",
  "configuration": {
	"schemeType": {
	  "enabled": true,
	  "headersDelimiter": ".",
	  "headers": [
		"X-Gravitee-Request-ID",
		"X-Header-Timestamp"
	  ]
	},
	"secret": "mySecret",
	"targetSignatureHeader": "X-HMAC-Signature",
	"algorithm": "HmacSHA256"
  }
}
----

== Http Status Code

|===
|Code |Message

.^| ```401```
| In case of:

* Missing or signature

* Request does not contain headers part of the signature

* Enforce HTTP headers not part of the signature
|===

== Errors

If you're looking to override the default response provided by the policy, you can do it
thanks to the response templates feature. These templates must be define at the API level (see `Response Templates`
from the `Proxy` menu).

Here are the error keys sent by this policy:

[cols="2*", options="header"]
|===
^|Key
^|Parameters

.^|WEBHOOK_SIGNATURE_INVALID_SIGNATURE
^.^|-

.^|WEBHOOK_SIGNATURE_NOT_FOUND
^.^|-

.^|WEBHOOK_SIGNATURE_NOT_BASE64
^.^|-

.^|WEBHOOK_ADDITIONAL_HEADERS_NOT_VALID
^.^|-

|===
